# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and Update
      run: |
        echo -n "0.1.$GITHUB_RUN_NUMBER" > VERSION
        echo "$GITHUB_RUN_NUMBER"
        pip install -q build
        python -m build -s
    - name: Upload Build Files
      uses: actions/upload-artifact@v2
      with:
        name: build_results
        path: dist/*
  build-wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
    - name: Download Build Files
      uses: actions/download-artifact@v2
      with:
        name: build_results
    - name: install-pip
      run: |
        yum install epel-release
        yum -y install pip
    - name: build-wheel
      run: |
        python -m pip wheel ./dist/*      

